#7921 core_coord: simplify merge logic in CoreRangeSet
Newer GCC threw a warning because there are paths that it couldn't tell
that x_start would always have been set.

When looking at the implementation, it seems easier to just overallocate
the grid array by one entry, and get rid of needing x_start to be optional
and conditional.

Error as produced by GCC 13 in Ubutnu 24.04:

In file included from ./tt_metal/impl/buffers/buffer.hpp:8,
                 from ./tt_metal/impl/program/program.hpp:11,
                 from tt_metal/impl/program/program.cpp:5:
./tt_metal/common/core_coord.h: In member function 'CoreRangeSet CoreRangeSet::merge(const std::set<CoreRange>&) const':
./tt_metal/common/core_coord.h:297:29: error: '*(unsigned int*)((char*)&x_start + offsetof(std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>))' may be used uninitialized [-Werror=maybe-uninitialized]
  297 |           ranges.push_back( CoreRange( {x_start.value(), y}, {max_x, y} ) );
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tt_metal/common/core_coord.h:284:33: note: '*(unsigned int*)((char*)&x_start + offsetof(std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>))' was declared here
  284 |         std::optional<unsigned> x_start;
      |                                 ^~~~~~~

Cc: Bill Teng <bteng@tenstorrent.com>
Signed-off-by: Olof Johansson <olofj@tenstorrent.com>